name: 🧹 Sentinel Submodule Cleaner

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: 🧠 Checkout du dépôt
        uses: actions/checkout@v4

      - name: 🧹 Supprimer toute référence de sous-module fantôme
        run: |
          echo "🔍 Nettoyage des anciens sous-modules Git..."
          git submodule deinit -f --all || true
          rm -rf .git/modules/akiprisaye || true
          git rm -f akiprisaye || true
          rm -rf akiprisaye || true
          echo "✅ Sous-modules nettoyés."

      - name: 🔒 Commit de nettoyage
        run: |
          git config --global user.name "sentinel-cleaner-bot"
          git config --global user.email "sentinel@system.local"
          git add -A
          git commit -m "🧹 Cleaned submodule references (akiprisaye removed)" || true
          git push origin main || true

      - name: ✅ Validation
        run: echo "🧠 Nettoyage terminé — aucune référence de sous-module restante."