name: Android Build Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Grant execute permission for gradlew
        working-directory: ./native-android-app
        run: chmod +x ./gradlew
      
      - name: Build APK (Debug)
        run: |
          cd native-android-app
          ./gradlew assembleDebug

