name: Android Build Check

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Grant execute permission for gradlew
        working-directory: ./native-android-app
        run: chmod +x ./gradlew
      
      - name: Build APK (Debug)
        working-directory: ./native-android-app
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SentinelQuantumVanguard-debug-apk
          path: native-android-app/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
      
      - name: Upload APK to GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: native-android-app/app/build/outputs/apk/debug/app-debug.apk

