name: Integrity Check

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run integrity script
        run: |
          if [ -f ""scripts/validation/integrity-check.ps1"" ]; then pwsh scripts/validation/integrity-check.ps1; fi

