name: 🛰️ Sentinel Backend Monitor

on:
  schedule:
    - cron: "*/10 * * * *"   # toutes les 10 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    name: 🔍 Surveillance Render Backend
    steps:
      - name: 🧠 Initialisation de l’environnement
        run: |
          echo "🔧 Démarrage du moniteur Sentinel Backend..."
          mkdir -p logs

      - name: 🌐 Vérification du statut Render
        id: ping
        run: |
          echo "⏱️ Test de latence et de disponibilité du backend..."
          URL="https://sentinel-quantum-vanguard-ai-pro.onrender.com"
          START=$(date +%s)
          HTTP_CODE=$(curl -s -o /tmp/result -w "%{http_code}" "$URL" || echo 000)
          END=$(date +%s)
          LATENCY=$((END - START))

          echo "Statut HTTP : $HTTP_CODE"
          echo "Latence : ${LATENCY}s"
          echo "http_code=$HTTP_CODE" >> $GITHUB_OUTPUT
          echo "latency=$LATENCY" >> $GITHUB_OUTPUT

          echo "$(date '+%d/%m/%Y %H:%M:%S') | Code : $HTTP_CODE | Latence : ${LATENCY}s" >> logs/backend-monitor.log

      - name: 🚨 Analyse des résultats
        if: ${{ steps.ping.outputs.http_code != '200' || steps.ping.outputs.latency > 10 }}
        run: |
          echo "⚠️ Backend Render instable ou en panne !"
          echo "Redéploiement automatique déclenché..."

          curl -X POST "https://api.render.com/v1/services/<SERVICE_ID>/deploys" \
               -H "Accept: application/json" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
               -d '{"clearCache":false}'

          echo "✅ Nouvelle instance Render déployée." >> logs/backend-monitor.log

      - name: ✅ Résultat sain
        if: ${{ steps.ping.outputs.http_code == '200' && steps.ping.outputs.latency <= 10 }}
        run: |
          echo "🟢 Backend opérationnel et rapide."
          echo "OK | $(date '+%d/%m/%Y %H:%M:%S')" >> logs/backend-monitor.log

      - name: 📡 Notification Telegram (optionnelle)
        if: always()
        run: |
          if [ -n "${{ secrets.TELEGRAM_WEBHOOK }}" ]; then
            MSG="🔔 Sentinel Backend : HTTP ${{ steps.ping.outputs.http_code }} | Latence ${{ steps.ping.outputs.latency }} s"
            curl -s -X POST ${{ secrets.TELEGRAM_WEBHOOK }} -d "text=$MSG"
          fi

      - name: 🗂️ Upload des logs (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: backend-monitor-logs
          path: logs/backend-monitor.log
