/**
 * Red Team Simulation Engine
 * 
 * LEGAL NOTICE:
 * "Offensive Security Simulation – Aucun accès non autorisé – Usage audit, formation et évaluation uniquement."
 * 
 * This module simulates offensive security scenarios based on MITRE ATT&CK framework.
 * NO REAL ATTACKS - SIMULATION ONLY
 * 
 * @version 1.0.0
 * @compliance ANSSI, NIST, MITRE ATT&CK
 */

/**
 * Red Team Scenario Interface
 */
export interface RedTeamScenario {
  id: string;
  name: string;
  description: string;
  mitreTactics: MITRETactic[];
  steps: SimulationStep[];
  expectedDetectionIndicators: DetectionIndicator[];
  impact: 'low' | 'medium' | 'critical';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  estimatedDuration: number; // minutes
}

/**
 * MITRE ATT&CK Tactic
 */
export interface MITRETactic {
  id: string;           // e.g., "TA0001"
  name: string;         // e.g., "Initial Access"
  techniques: MITRETechnique[];
}

/**
 * MITRE ATT&CK Technique
 */
export interface MITRETechnique {
  id: string;           // e.g., "T1566"
  name: string;         // e.g., "Phishing"
  subTechniques?: string[];
  platform: string[];   // e.g., ["Windows", "Linux"]
  dataSource: string[]; // e.g., ["Email", "Network Traffic"]
}

/**
 * Simulation Step
 */
export interface SimulationStep {
  stepNumber: number;
  description: string;
  techniqueId: string;  // Links to MITRE Technique
  action: SimulationAction;
  expectedResult: string;
  timingOffset: number; // seconds from scenario start
  simulated: true;      // ALWAYS true - no real execution
}

/**
 * Simulation Action (LOGICAL ONLY - NO REAL EXECUTION)
 */
export interface SimulationAction {
  type: 'scan' | 'access' | 'execution' | 'persistence' | 'exfiltration' | 'impact';
  parameters: Record<string, any>;
  logicalOutcome: string;
}

/**
 * Detection Indicator
 */
export interface DetectionIndicator {
  type: 'network' | 'file' | 'process' | 'registry' | 'behavioral';
  indicator: string;
  confidence: 'low' | 'medium' | 'high';
  techniqueId: string;
}

/**
 * Simulation Result
 */
export interface SimulationResult {
  scenarioId: string;
  startTime: Date;
  endTime: Date;
  duration: number; // milliseconds
  events: SOCEvent[];
  detectionScore: number; // 0-100
  tacticsUsed: string[];
  techniquesUsed: string[];
  success: boolean;
  metrics: SimulationMetrics;
}

/**
 * SOC Event (Generated by simulation)
 */
export interface SOCEvent {
  id: string;
  timestamp: Date;
  type: 'authentication' | 'network' | 'privilege' | 'configuration' | 'data';
  source: 'red-team-simulation';
  severity: 'info' | 'low' | 'medium' | 'high' | 'critical';
  techniqueId: string;
  tacticId: string;
  description: string;
  metadata: Record<string, any>;
  simulated: true; // ALWAYS true
}

/**
 * Simulation Metrics
 */
export interface SimulationMetrics {
  eventsGenerated: number;
  meanTimeToDetect: number; // milliseconds (simulated)
  detectionRate: number; // percentage
  coverageMITRE: number; // percentage of MITRE matrix covered
}

/**
 * Red Team Engine
 * 
 * Core engine for running offensive security simulations
 */
export class RedTeamEngine {
  private scenarios: Map<string, RedTeamScenario> = new Map();
  private activeSimulations: Map<string, SimulationResult> = new Map();
  
  constructor() {
    console.log('🔴 Red Team Engine initialized');
    console.log('⚠️ LEGAL MODE: Simulations only - No real attacks');
  }

  /**
   * Load scenario from JSON
   */
  loadScenario(scenarioData: RedTeamScenario): void {
    // Validate scenario compliance
    if (!this.validateScenarioCompliance(scenarioData)) {
      throw new Error('Scenario failed compliance validation');
    }
    
    this.scenarios.set(scenarioData.id, scenarioData);
    console.log(`✅ Scenario loaded: ${scenarioData.name}`);
  }

  /**
   * Validate scenario compliance (CRITICAL SECURITY CHECK)
   */
  private validateScenarioCompliance(scenario: RedTeamScenario): boolean {
    // Check 1: All steps must be marked as simulated
    for (const step of scenario.steps) {
      if (step.simulated !== true) {
        console.error('❌ COMPLIANCE VIOLATION: Step not marked as simulated');
        return false;
      }
    }

    // Check 2: No dangerous action types
    const dangerousActions = ['execute', 'exploit', 'compromise'];
    for (const step of scenario.steps) {
      const actionStr = JSON.stringify(step.action).toLowerCase();
      for (const dangerous of dangerousActions) {
        if (actionStr.includes(dangerous)) {
          console.error(`❌ COMPLIANCE VIOLATION: Dangerous action detected: ${dangerous}`);
          return false;
        }
      }
    }

    // Check 3: Impact must be documented
    if (!scenario.impact) {
      console.error('❌ COMPLIANCE VIOLATION: Impact not documented');
      return false;
    }

    return true;
  }

  /**
   * Run simulation
   */
  async runSimulation(scenarioId: string): Promise<SimulationResult> {
    const scenario = this.scenarios.get(scenarioId);
    
    if (!scenario) {
      throw new Error(`Scenario not found: ${scenarioId}`);
    }

    console.log(`🚀 Starting simulation: ${scenario.name}`);
    
    const startTime = new Date();
    const events: SOCEvent[] = [];
    const tacticsUsed = new Set<string>();
    const techniquesUsed = new Set<string>();

    // Execute simulation steps
    for (const step of scenario.steps) {
      await this.delay(step.timingOffset * 1000);
      
      // Generate SOC events for this step
      const stepEvents = this.generateEventsForStep(step, scenario);
      events.push(...stepEvents);
      
      // Track MITRE coverage
      techniquesUsed.add(step.techniqueId);
      const tactic = this.findTacticForTechnique(scenario, step.techniqueId);
      if (tactic) {
        tacticsUsed.add(tactic.id);
      }
      
      console.log(`  ✓ Step ${step.stepNumber}: ${step.description}`);
    }

    const endTime = new Date();
    const duration = endTime.getTime() - startTime.getTime();

    // Calculate metrics
    const metrics = this.calculateMetrics(events, scenario);

    const result: SimulationResult = {
      scenarioId: scenario.id,
      startTime,
      endTime,
      duration,
      events,
      detectionScore: this.calculateDetectionScore(events, scenario),
      tacticsUsed: Array.from(tacticsUsed),
      techniquesUsed: Array.from(techniquesUsed),
      success: true,
      metrics
    };

    this.activeSimulations.set(scenarioId, result);
    
    console.log(`✅ Simulation completed: ${scenario.name}`);
    console.log(`   Duration: ${duration}ms`);
    console.log(`   Events: ${events.length}`);
    console.log(`   Detection Score: ${result.detectionScore}/100`);

    return result;
  }

  /**
   * Generate SOC events for a simulation step
   */
  private generateEventsForStep(step: SimulationStep, scenario: RedTeamScenario): SOCEvent[] {
    const events: SOCEvent[] = [];
    const baseTime = new Date();
    
    // Number of events depends on action type
    const eventCount = this.getEventCountForAction(step.action.type);
    
    for (let i = 0; i < eventCount; i++) {
      const event: SOCEvent = {
        id: `evt-${Date.now()}-${i}`,
        timestamp: new Date(baseTime.getTime() + i * 100),
        type: this.mapActionToEventType(step.action.type),
        source: 'red-team-simulation',
        severity: this.determineSeverity(step, scenario),
        techniqueId: step.techniqueId,
        tacticId: this.findTacticForTechnique(scenario, step.techniqueId)?.id || 'unknown',
        description: this.generateEventDescription(step),
        metadata: {
          stepNumber: step.stepNumber,
          actionType: step.action.type,
          parameters: step.action.parameters,
          expectedResult: step.expectedResult
        },
        simulated: true // ALWAYS true
      };
      
      events.push(event);
    }
    
    return events;
  }

  /**
   * Get event count based on action type
   */
  private getEventCountForAction(actionType: string): number {
    const counts: Record<string, number> = {
      'scan': 5,
      'access': 3,
      'execution': 4,
      'persistence': 2,
      'exfiltration': 6,
      'impact': 8
    };
    return counts[actionType] || 2;
  }

  /**
   * Map simulation action to SOC event type
   */
  private mapActionToEventType(actionType: string): SOCEvent['type'] {
    const mapping: Record<string, SOCEvent['type']> = {
      'scan': 'network',
      'access': 'authentication',
      'execution': 'privilege',
      'persistence': 'configuration',
      'exfiltration': 'data',
      'impact': 'configuration'
    };
    return mapping[actionType] || 'network';
  }

  /**
   * Determine event severity
   */
  private determineSeverity(step: SimulationStep, scenario: RedTeamScenario): SOCEvent['severity'] {
    if (scenario.impact === 'critical') return 'critical';
    if (scenario.impact === 'medium') return 'high';
    
    const severityByAction: Record<string, SOCEvent['severity']> = {
      'scan': 'low',
      'access': 'medium',
      'execution': 'high',
      'persistence': 'high',
      'exfiltration': 'critical',
      'impact': 'critical'
    };
    
    return severityByAction[step.action.type] || 'medium';
  }

  /**
   * Generate event description
   */
  private generateEventDescription(step: SimulationStep): string {
    const templates: Record<string, string> = {
      'scan': 'Network scanning activity detected',
      'access': 'Authentication attempt from unusual location',
      'execution': 'Suspicious process execution detected',
      'persistence': 'Configuration change detected',
      'exfiltration': 'Large data transfer to external destination',
      'impact': 'Critical system modification detected'
    };
    
    return templates[step.action.type] || `Simulated ${step.action.type} detected`;
  }

  /**
   * Find tactic for a technique
   */
  private findTacticForTechnique(scenario: RedTeamScenario, techniqueId: string): MITRETactic | undefined {
    for (const tactic of scenario.mitreTactics) {
      if (tactic.techniques.some(t => t.id === techniqueId)) {
        return tactic;
      }
    }
    return undefined;
  }

  /**
   * Calculate simulation metrics
   */
  private calculateMetrics(events: SOCEvent[], scenario: RedTeamScenario): SimulationMetrics {
    // Simulate detection times
    const detectionTimes = events.map(() => Math.random() * 5000 + 1000);
    const meanTimeToDetect = detectionTimes.reduce((a, b) => a + b, 0) / detectionTimes.length;
    
    // Simulate detection rate (70-95%)
    const detectionRate = 70 + Math.random() * 25;
    
    // Calculate MITRE coverage
    const totalTechniques = scenario.mitreTactics.reduce((sum, tactic) => 
      sum + tactic.techniques.length, 0
    );
    const coverageMITRE = (totalTechniques / 193) * 100; // 193 total MITRE techniques
    
    return {
      eventsGenerated: events.length,
      meanTimeToDetect,
      detectionRate,
      coverageMITRE
    };
  }

  /**
   * Calculate detection score
   */
  private calculateDetectionScore(events: SOCEvent[], scenario: RedTeamScenario): number {
    // Base score
    let score = 50;
    
    // Bonus for number of events (more events = better visibility)
    score += Math.min(events.length / 2, 20);
    
    // Bonus for coverage
    const tacticCount = new Set(events.map(e => e.tacticId)).size;
    score += tacticCount * 5;
    
    // Bonus for severity distribution
    const criticalCount = events.filter(e => e.severity === 'critical').length;
    score += Math.min(criticalCount, 10);
    
    return Math.min(Math.round(score), 100);
  }

  /**
   * Get simulation results
   */
  getSimulationResult(scenarioId: string): SimulationResult | undefined {
    return this.activeSimulations.get(scenarioId);
  }

  /**
   * Get all scenarios
   */
  getAllScenarios(): RedTeamScenario[] {
    return Array.from(this.scenarios.values());
  }

  /**
   * Delay helper
   */
  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  /**
   * Export simulation results to JSON
   */
  exportToJSON(scenarioId: string): string {
    const result = this.activeSimulations.get(scenarioId);
    if (!result) {
      throw new Error(`No results found for scenario: ${scenarioId}`);
    }
    return JSON.stringify(result, null, 2);
  }

  /**
   * Export simulation results to CSV
   */
  exportToCSV(scenarioId: string): string {
    const result = this.activeSimulations.get(scenarioId);
    if (!result) {
      throw new Error(`No results found for scenario: ${scenarioId}`);
    }

    const headers = ['Timestamp', 'Type', 'Severity', 'Technique ID', 'Tactic ID', 'Description'];
    const rows = result.events.map(event => [
      event.timestamp.toISOString(),
      event.type,
      event.severity,
      event.techniqueId,
      event.tacticId,
      event.description
    ]);

    return [headers, ...rows]
      .map(row => row.join(','))
      .join('\n');
  }
}

// Export singleton instance
export const redTeamEngine = new RedTeamEngine();

// Browser compatibility
if (typeof window !== 'undefined') {
  (window as any).RedTeamEngine = RedTeamEngine;
  (window as any).redTeamEngine = redTeamEngine;
}

console.log('🔴 Red Team Simulation Engine loaded');
console.log('⚖️ LEGAL NOTICE: Offensive Security Simulation – Aucun accès non autorisé');
console.log('📋 Usage: audit, formation et évaluation uniquement');
