import {
  calculateExpectedDetectionRate,
  calculateTechniqueCoverage,
  deterministicLatencyMs
} from './deterministicMetrics.js';

/**
 * Red Team Simulation Engine
 *
 * SIMULATION BOUNDARY:
 * Offensive-security scenarios in this module are logical simulations for
 * authorized audit, training and evaluation. This module performs no real
 * attack or privileged execution.
 *
 * This module simulates offensive security scenarios based on MITRE ATT&CK framework.
 * NO REAL ATTACKS - SIMULATION ONLY
 *
 * @version 1.0.0
 * @references ANSSI, NIST, MITRE ATT&CK
 */

/**
 * Red Team Scenario Interface
 */
export interface RedTeamScenario {
  id: string;
  name: string;
  description: string;
  mitreTactics: MITRETactic[];
  steps: SimulationStep[];
  expectedDetectionIndicators: DetectionIndicator[];
  impact: 'low' | 'medium' | 'critical';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  estimatedDuration: number; // minutes
}

/**
 * MITRE ATT&CK Tactic
 */
export interface MITRETactic {
  id: string;
  name: string;
  techniques: MITRETechnique[];
}

/**
 * MITRE ATT&CK Technique
 */
export interface MITRETechnique {
  id: string;
  name: string;
  subTechniques?: string[];
  platform: string[];
  dataSource: string[];
}

/**
 * Simulation Step
 */
export interface SimulationStep {
  stepNumber: number;
  description: string;
  techniqueId: string;
  action: SimulationAction;
  expectedResult: string;
  timingOffset: number;
  simulated: true;
}

/**
 * Simulation Action (LOGICAL ONLY - NO REAL EXECUTION)
 */
export interface SimulationAction {
  type: 'scan' | 'access' | 'execution' | 'persistence' | 'exfiltration' | 'impact';
  parameters: Record<string, any>;
  logicalOutcome: string;
}

/**
 * Detection Indicator
 */
export interface DetectionIndicator {
  type: 'network' | 'file' | 'process' | 'registry' | 'behavioral';
  indicator: string;
  confidence: 'low' | 'medium' | 'high';
  techniqueId: string;
}

/**
 * Simulation Result
 */
export interface SimulationResult {
  scenarioId: string;
  startTime: Date;
  endTime: Date;
  duration: number;
  events: SOCEvent[];
  detectionScore: number;
  tacticsUsed: string[];
  techniquesUsed: string[];
  success: boolean;
  metrics: SimulationMetrics;
}

/**
 * SOC Event (Generated by simulation)
 */
export interface SOCEvent {
  id: string;
  timestamp: Date;
  type: 'authentication' | 'network' | 'privilege' | 'configuration' | 'data';
  source: 'red-team-simulation';
  severity: 'info' | 'low' | 'medium' | 'high' | 'critical';
  techniqueId: string;
  tacticId: string;
  description: string;
  metadata: Record<string, any>;
  simulated: true;
}

/**
 * Simulation Metrics
 */
export interface SimulationMetrics {
  eventsGenerated: number;
  meanTimeToDetect: number; // deterministic simulated milliseconds
  detectionRate: number; // expected indicator technique coverage percentage
  coverageMITRE: number; // declared scenario technique coverage percentage
}

/**
 * Red Team Engine
 *
 * Core engine for running offensive security simulations
 */
export class RedTeamEngine {
  private scenarios: Map<string, RedTeamScenario> = new Map();
  private activeSimulations: Map<string, SimulationResult> = new Map();

  constructor() {
    console.log('🔴 Red Team Engine initialized');
    console.log('⚠️ CONTROLLED SIMULATION MODE: No real attacks or privileged execution');
  }

  /**
   * Load scenario from JSON
   */
  loadScenario(scenarioData: RedTeamScenario): void {
    if (!this.validateScenarioCompliance(scenarioData)) {
      throw new Error('Scenario failed simulation-boundary validation');
    }

    this.scenarios.set(scenarioData.id, scenarioData);
    console.log(`✅ Scenario loaded: ${scenarioData.name}`);
  }

  /**
   * Validate scenario simulation boundary (CRITICAL SECURITY CHECK)
   */
  private validateScenarioCompliance(scenario: RedTeamScenario): boolean {
    for (const step of scenario.steps) {
      if (step.simulated !== true) {
        console.error('❌ SIMULATION BOUNDARY: Step not marked as simulated');
        return false;
      }
    }

    const dangerousActions = ['execute', 'exploit', 'compromise'];
    for (const step of scenario.steps) {
      const actionStr = JSON.stringify(step.action).toLowerCase();
      for (const dangerous of dangerousActions) {
        if (actionStr.includes(dangerous)) {
          console.error(`❌ SIMULATION BOUNDARY: Dangerous action detected: ${dangerous}`);
          return false;
        }
      }
    }

    if (!scenario.impact) {
      console.error('❌ SIMULATION BOUNDARY: Impact not documented');
      return false;
    }

    return true;
  }

  /**
   * Run simulation
   */
  async runSimulation(scenarioId: string): Promise<SimulationResult> {
    const scenario = this.scenarios.get(scenarioId);

    if (!scenario) {
      throw new Error(`Scenario not found: ${scenarioId}`);
    }

    console.log(`🚀 Starting simulation: ${scenario.name}`);

    const startTime = new Date();
    const events: SOCEvent[] = [];
    const tacticsUsed = new Set<string>();
    const techniquesUsed = new Set<string>();

    for (const step of scenario.steps) {
      await this.delay(step.timingOffset * 1000);

      const stepEvents = this.generateEventsForStep(step, scenario);
      events.push(...stepEvents);

      techniquesUsed.add(step.techniqueId);
      const tactic = this.findTacticForTechnique(scenario, step.techniqueId);
      if (tactic) {
        tacticsUsed.add(tactic.id);
      }

      console.log(`  ✓ Step ${step.stepNumber}: ${step.description}`);
    }

    const endTime = new Date();
    const duration = endTime.getTime() - startTime.getTime();
    const metrics = this.calculateMetrics(events, scenario);

    const result: SimulationResult = {
      scenarioId: scenario.id,
      startTime,
      endTime,
      duration,
      events,
      detectionScore: this.calculateDetectionScore(events, scenario),
      tacticsUsed: Array.from(tacticsUsed),
      techniquesUsed: Array.from(techniquesUsed),
      success: true,
      metrics
    };

    this.activeSimulations.set(scenarioId, result);

    console.log(`✅ Simulation completed: ${scenario.name}`);
    console.log(`   Duration: ${duration}ms`);
    console.log(`   Events: ${events.length}`);
    console.log(`   Detection Score: ${result.detectionScore}/100`);

    return result;
  }

  /**
   * Generate SOC events for a simulation step
   */
  private generateEventsForStep(step: SimulationStep, scenario: RedTeamScenario): SOCEvent[] {
    const events: SOCEvent[] = [];
    const baseTime = new Date();
    const eventCount = this.getEventCountForAction(step.action.type);

    for (let i = 0; i < eventCount; i++) {
      const event: SOCEvent = {
        id: `evt-${Date.now()}-${i}`,
        timestamp: new Date(baseTime.getTime() + i * 100),
        type: this.mapActionToEventType(step.action.type),
        source: 'red-team-simulation',
        severity: this.determineSeverity(step, scenario),
        techniqueId: step.techniqueId,
        tacticId: this.findTacticForTechnique(scenario, step.techniqueId)?.id || 'unknown',
        description: this.generateEventDescription(step),
        metadata: {
          stepNumber: step.stepNumber,
          actionType: step.action.type,
          parameters: step.action.parameters,
          expectedResult: step.expectedResult
        },
        simulated: true
      };

      events.push(event);
    }

    return events;
  }

  private getEventCountForAction(actionType: string): number {
    const counts: Record<string, number> = {
      scan: 5,
      access: 3,
      execution: 4,
      persistence: 2,
      exfiltration: 6,
      impact: 8
    };
    return counts[actionType] || 2;
  }

  private mapActionToEventType(actionType: string): SOCEvent['type'] {
    const mapping: Record<string, SOCEvent['type']> = {
      scan: 'network',
      access: 'authentication',
      execution: 'privilege',
      persistence: 'configuration',
      exfiltration: 'data',
      impact: 'configuration'
    };
    return mapping[actionType] || 'network';
  }

  private determineSeverity(step: SimulationStep, scenario: RedTeamScenario): SOCEvent['severity'] {
    if (scenario.impact === 'critical') return 'critical';
    if (scenario.impact === 'medium') return 'high';

    const severityByAction: Record<string, SOCEvent['severity']> = {
      scan: 'low',
      access: 'medium',
      execution: 'high',
      persistence: 'high',
      exfiltration: 'critical',
      impact: 'critical'
    };

    return severityByAction[step.action.type] || 'medium';
  }

  private generateEventDescription(step: SimulationStep): string {
    const templates: Record<string, string> = {
      scan: 'Network scanning activity detected',
      access: 'Authentication attempt from unusual location',
      execution: 'Suspicious process execution detected',
      persistence: 'Configuration change detected',
      exfiltration: 'Large data transfer to external destination',
      impact: 'Critical system modification detected'
    };

    return templates[step.action.type] || `Simulated ${step.action.type} detected`;
  }

  private findTacticForTechnique(scenario: RedTeamScenario, techniqueId: string): MITRETactic | undefined {
    for (const tactic of scenario.mitreTactics) {
      if (tactic.techniques.some(t => t.id === techniqueId)) {
        return tactic;
      }
    }
    return undefined;
  }

  /**
   * Calculate deterministic, scenario-relative simulation metrics.
   */
  private calculateMetrics(events: SOCEvent[], scenario: RedTeamScenario): SimulationMetrics {
    const eventTechniqueIds = events.map(event => event.techniqueId);

    const meanTimeToDetect = events.length > 0
      ? events
        .map((event, index) => deterministicLatencyMs(
          scenario.id,
          event.techniqueId,
          event.tacticId,
          index
        ))
        .reduce((a, b) => a + b, 0) / events.length
      : 0;

    const expectedTechniqueIds = scenario.expectedDetectionIndicators
      .map(indicator => indicator.techniqueId);
    const detectionRate = calculateExpectedDetectionRate(
      eventTechniqueIds,
      expectedTechniqueIds
    );

    const declaredTechniqueIds = scenario.mitreTactics.flatMap(tactic =>
      tactic.techniques.map(technique => technique.id)
    );
    const coverageMITRE = calculateTechniqueCoverage(
      eventTechniqueIds,
      declaredTechniqueIds
    );

    return {
      eventsGenerated: events.length,
      meanTimeToDetect,
      detectionRate,
      coverageMITRE
    };
  }

  private calculateDetectionScore(events: SOCEvent[], scenario: RedTeamScenario): number {
    let score = 50;
    score += Math.min(events.length / 2, 20);

    const tacticCount = new Set(events.map(e => e.tacticId)).size;
    score += tacticCount * 5;

    const criticalCount = events.filter(e => e.severity === 'critical').length;
    score += Math.min(criticalCount, 10);

    return Math.min(Math.round(score), 100);
  }

  getSimulationResult(scenarioId: string): SimulationResult | undefined {
    return this.activeSimulations.get(scenarioId);
  }

  getAllScenarios(): RedTeamScenario[] {
    return Array.from(this.scenarios.values());
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  exportToJSON(scenarioId: string): string {
    const result = this.activeSimulations.get(scenarioId);
    if (!result) {
      throw new Error(`No results found for scenario: ${scenarioId}`);
    }
    return JSON.stringify(result, null, 2);
  }

  exportToCSV(scenarioId: string): string {
    const result = this.activeSimulations.get(scenarioId);
    if (!result) {
      throw new Error(`No results found for scenario: ${scenarioId}`);
    }

    const headers = ['Timestamp', 'Type', 'Severity', 'Technique ID', 'Tactic ID', 'Description'];
    const rows = result.events.map(event => [
      event.timestamp.toISOString(),
      event.type,
      event.severity,
      event.techniqueId,
      event.tacticId,
      event.description
    ]);

    return [headers, ...rows]
      .map(row => row.join(','))
      .join('\n');
  }
}

export const redTeamEngine = new RedTeamEngine();

if (typeof window !== 'undefined') {
  (window as any).RedTeamEngine = RedTeamEngine;
  (window as any).redTeamEngine = redTeamEngine;
}

console.log('🔴 Red Team Simulation Engine loaded');
console.log('⚠️ SIMULATION BOUNDARY: Offensive-security scenarios are logical only');
console.log('📋 Usage boundary: authorized audit, training and evaluation');