name: 🧠 Sentinel Cognitive Monitor AI — Deep Site Validation

on:
  schedule:
    - cron: "*/30 * * * *" # Vérification toutes les 30 minutes
  workflow_dispatch:

jobs:
  cognitive-scan:
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Analyse cognitive du site Sentinel
        id: scan
        run: |
          URL="https://sentinelquantumvanguardaipro.pages.dev"
          echo "🧠 Analyse du contenu du site : $URL"
          RESPONSE=$(curl -s -L $URL)
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" $URL)

          echo "Code HTTP : $STATUS" 
          echo "Longueur de la réponse : $(echo "$RESPONSE" | wc -c)"

          if [ "$STATUS" -ne 200 ]; then
            echo "⚠️ Site renvoie un code HTTP anormal ($STATUS)"
            echo "result=failure" >> $GITHUB_OUTPUT
            echo "details=HTTP Status $STATUS" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Détection de contenu suspect
          if echo "$RESPONSE" | grep -iqE "error|404|not found|deployment failed|vite error|500"; then
            echo "⚠️ Anomalie détectée dans le contenu."
            echo "result=failure" >> $GITHUB_OUTPUT
            echo "details=Anomalie de contenu HTML détectée" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [ "$(echo "$RESPONSE" | wc -c)" -lt 500 ]; then
            echo "⚠️ Réponse trop courte (contenu incomplet ou vide)"
            echo "result=failure" >> $GITHUB_OUTPUT
            echo "details=Réponse trop courte (<500 octets)" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "✅ Analyse cognitive réussie : contenu HTML cohérent."
          echo "result=success" >> $GITHUB_OUTPUT
          echo "details=OK" >> $GITHUB_OUTPUT

      - name: ✅ Notification Telegram (succès)
        if: steps.scan.outputs.result == 'success'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MSG="✅ *Sentinel Cognitive Monitor AI* : site fonctionnel et cohérent.%0A🧩 Analyse réussie.%0A🌐 https://sentinelquantumvanguardaipro.pages.dev"
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAM_CHAT_ID}" \
            -d "text=$MSG" \
            -d "parse_mode=Markdown"

      - name: 🚨 Notification Telegram (anomalie détectée)
        if: steps.scan.outputs.result == 'failure'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          DETAILS="${{ steps.scan.outputs.details }}"
          MSG="🚨 *ALERTE IA SENTINEL* : anomalie détectée sur le site.%0A🔍 Détail : $DETAILS%0A⚠️ Contenu suspect détecté.%0A🌐 https://sentinelquantumvanguardaipro.pages.dev"
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAM_CHAT_ID}" \
            -d "text=$MSG" \
            -d "parse_mode=Markdown"