import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, cpSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
const repoRoot=resolve(import.meta.dirname,'..');
function run(script,cwd,env={}){return spawnSync(process.execPath,[join(cwd,'scripts',script)],{cwd,encoding:'utf8',env:{...process.env,...env}});}
const ci=(attempt='1',runId='123')=>({GITHUB_ACTIONS:'true',GITHUB_REPOSITORY:'teetee971/SentinelQuantumVanguardAiPro',GITHUB_SHA:'abc123',GITHUB_WORKFLOW:'Sentinel Autonomous Maintenance',GITHUB_WORKFLOW_REF:'teetee971/SentinelQuantumVanguardAiPro/.github/workflows/autonomous-maintenance.yml@refs/heads/main',GITHUB_RUN_ID:runId,GITHUB_RUN_ATTEMPT:attempt,GITHUB_REF:'refs/heads/main',GITHUB_EVENT_NAME:'schedule'});
function fixture(){const root=mkdtempSync(join(tmpdir(),'sentinel-trust-'));mkdirSync(join(root,'scripts'),{recursive:true});mkdirSync(join(root,'artifacts','autonomous-engineering'),{recursive:true});for(const file of ['evidence-trust.js','autonomous-diagnostic.js','autonomous-remediation-plan.js'])cpSync(join(repoRoot,'scripts',file),join(root,'scripts',file));return root;}
function writeReport(root,runId='123',attempt='1',commit='abc123'){writeFileSync(join(root,'artifacts','autonomous-engineering','latest.json'),JSON.stringify({repository:'teetee971/SentinelQuantumVanguardAiPro',commit,provenance:{repository:'teetee971/SentinelQuantumVanguardAiPro',commit,workflow:'Sentinel Autonomous Maintenance',workflow_ref:'teetee971/SentinelQuantumVanguardAiPro/.github/workflows/autonomous-maintenance.yml@refs/heads/main',run_id:runId,run_attempt:attempt,ref:'refs/heads/main',event:'schedule'},checks:[{name:'build',status:'FAIL',exit_code:1,stderr:'build failed'}]},null,2));}
test('forged verification is rejected and trusted deterministic failure remains PLAN_ONLY',()=>{const root=fixture();try{writeReport(root);assert.equal(run('evidence-trust.js',root,ci()).status,0);const ep=join(root,'artifacts','autonomous-engineering','evidence.json');const evidence=JSON.parse(readFileSync(ep,'utf8'));assert.equal(evidence.verification_level,'CI_VERIFIED');assert.equal(run('autonomous-diagnostic.js',root,ci()).status,0);const dp=join(root,'artifacts','autonomous-engineering','diagnosis.json');const diagnosis=JSON.parse(readFileSync(dp,'utf8'));assert.equal(diagnosis.overall,'REMEDIATION_CANDIDATE');assert.equal(diagnosis.failed_checks[0].action,'PLAN_ONLY');writeFileSync(ep,JSON.stringify({...evidence,verification_level:'PRODUCTION_VERIFIED'},null,2));assert.equal(run('autonomous-diagnostic.js',root,ci()).status,2);assert.equal(JSON.parse(readFileSync(dp,'utf8')).overall,'BLOCKED');assert.equal(run('autonomous-remediation-plan.js',root,ci()).status,2);assert.deepEqual(JSON.parse(readFileSync(join(root,'artifacts','autonomous-engineering','remediation-plan.json'),'utf8')).plans,[]);}finally{rmSync(root,{recursive:true,force:true});}});
test('replay from another run id is blocked even when commit is identical',()=>{const root=fixture();try{writeReport(root,'123','1');assert.equal(run('evidence-trust.js',root,ci('1','123')).status,0);assert.equal(run('autonomous-diagnostic.js',root,ci('1','999')).status,2);assert.equal(JSON.parse(readFileSync(join(root,'artifacts','autonomous-engineering','diagnosis.json'),'utf8')).overall,'BLOCKED');}finally{rmSync(root,{recursive:true,force:true});}});
test('replay from another rerun attempt is blocked',()=>{const root=fixture();try{writeReport(root,'123','1');assert.equal(run('evidence-trust.js',root,ci('1','123')).status,0);assert.equal(run('autonomous-diagnostic.js',root,ci('2','123')).status,2);assert.equal(JSON.parse(readFileSync(join(root,'artifacts','autonomous-engineering','diagnosis.json'),'utf8')).overall,'BLOCKED');}finally{rmSync(root,{recursive:true,force:true});}});
test('mixed artifact chain is blocked after diagnosis is replaced',()=>{const root=fixture();try{writeReport(root);assert.equal(run('evidence-trust.js',root,ci()).status,0);assert.equal(run('autonomous-diagnostic.js',root,ci()).status,0);assert.equal(run('autonomous-remediation-plan.js',root,ci()).status,0);const dp=join(root,'artifacts','autonomous-engineering','diagnosis.json');const diagnosis=JSON.parse(readFileSync(dp,'utf8'));writeFileSync(dp,JSON.stringify({...diagnosis,generated_at:new Date(Date.now()+1000).toISOString()},null,2));assert.equal(run('autonomous-remediation-plan.js',root,ci()).status,2);assert.deepEqual(JSON.parse(readFileSync(join(root,'artifacts','autonomous-engineering','remediation-plan.json'),'utf8')).plans,[]);}finally{rmSync(root,{recursive:true,force:true});}});
test('mixed report and evidence are blocked even when repository and commit match',()=>{const root=fixture();try{writeReport(root,'123','1','abc123');assert.equal(run('evidence-trust.js',root,ci('1','123')).status,0);const oldEvidence=readFileSync(join(root,'artifacts','autonomous-engineering','evidence.json'),'utf8');writeReport(root,'124','1','abc123');writeFileSync(join(root,'artifacts','autonomous-engineering','evidence.json'),oldEvidence);assert.equal(run('autonomous-diagnostic.js',root,ci('1','124')).status,2);assert.equal(JSON.parse(readFileSync(join(root,'artifacts','autonomous-engineering','diagnosis.json'),'utf8')).overall,'BLOCKED');}finally{rmSync(root,{recursive:true,force:true});}});
