#!/usr/bin/env python3
"""Render bounded Sentinel domain lists into Unbound local-zone policy."""

from __future__ import annotations

import argparse
from pathlib import Path
import re

MAX_BYTES = 8 * 1024 * 1024
MAX_LINES = 400_000
MAX_BLOCK_RULES = 250_000
MAX_ALLOW_RULES = 10_000


def normalize_domain(raw: str) -> str | None:
    value = raw.split("#", 1)[0].strip()
    if not value:
        return None

    parts = value.split()
    if len(parts) == 2 and parts[0] in {"0.0.0.0", "127.0.0.1"}:
        value = parts[1]
    elif len(parts) != 1:
        return None

    value = value.strip().rstrip(".")
    try:
        value = value.encode("idna").decode("ascii").lower()
    except UnicodeError:
        return None

    if len(value) > 253 or "." not in value:
        return None

    labels = value.split(".")
    if any(
        not label
        or len(label) > 63
        or label.startswith("-")
        or label.endswith("-")
        or re.fullmatch(r"[a-z0-9-]+", label) is None
        for label in labels
    ):
        return None
    return value


def load_domains(path: Path, max_rules: int) -> set[str]:
    if path.stat().st_size > MAX_BYTES:
        raise ValueError(f"{path} exceeds {MAX_BYTES} bytes")
    raw = path.read_bytes()
    text = raw.decode("utf-8", errors="strict")
    values: set[str] = set()
    for index, line in enumerate(text.splitlines()):
        if index >= MAX_LINES:
            raise ValueError(f"{path} exceeds {MAX_LINES} lines")
        normalized = normalize_domain(line)
        if normalized:
            values.add(normalized)
            if len(values) > max_rules:
                raise ValueError(f"{path} exceeds {max_rules} accepted rules")
    return values


def render_policy(blocked: set[str], allowed: set[str]) -> str:
    effective_blocked = blocked - allowed
    lines = [
        "# Generated by Sentinel. Do not edit manually.",
        "server:",
    ]
    lines.extend(
        f'    local-zone: "{domain}." always_nxdomain'
        for domain in sorted(effective_blocked)
    )
    lines.extend(
        f'    local-zone: "{domain}." always_transparent'
        for domain in sorted(allowed)
    )
    return "\n".join(lines) + "\n"


def build_policy(blocklist: Path, allowlist: Path) -> tuple[str, int, int]:
    blocked = load_domains(blocklist, MAX_BLOCK_RULES)
    allowed = load_domains(allowlist, MAX_ALLOW_RULES)
    text = render_policy(blocked, allowed)
    return text, len(blocked - allowed), len(allowed)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--blocklist", required=True, type=Path)
    parser.add_argument("--allowlist", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    policy, blocked_count, allowed_count = build_policy(
        args.blocklist, args.allowlist
    )
    args.output.write_text(policy, encoding="utf-8")
    print(
        f"Generated {blocked_count} blocked and "
        f"{allowed_count} allowed domains"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
