name: ⚛️ Wave 12 – Quantum Redundancy Matrix (Auto Failover + Multi-Instance Sync)

on:
  schedule:
    - cron: "*/30 * * * *"   # toutes les 30 minutes
  workflow_dispatch:

jobs:
  redundancy:
    runs-on: ubuntu-latest
    name: ⚙️ Sentinel Quantum Redundancy Manager
    steps:
      - name: 🚀 Initialisation
        run: |
          echo "⚛️ Initialisation de la Redundancy Matrix"
          mkdir -p logs
          echo "$(date '+%F %T') | Début Wave 12" >> logs/redundancy.log

      - name: 🧩 Vérification de l’état des instances
        id: healthcheck
        run: |
          declare -A SERVICES=(
            ["render"]="https://<RENDER_URL>"
            ["cloudflare"]="https://<WORKER_URL>"
            ["firebase"]="https://<FIREBASE_URL>"
          )

          FAILCOUNT=0
          for svc in "${!SERVICES[@]}"; do
            URL=${SERVICES[$svc]}
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
            echo "$(date '+%T') | $svc -> $STATUS" >> logs/redundancy.log
            [[ $STATUS -ne 200 ]] && ((FAILCOUNT++))
          done
          echo "failcount=$FAILCOUNT" >> $GITHUB_OUTPUT

      - name: 🔁 Synchronisation et réparation
        if: ${{ steps.healthcheck.outputs.failcount > 0 }}
        run: |
          echo "⚠️ Une ou plusieurs instances hors ligne. Déclenchement rebuild..."
          # Redeploy Render
          curl -X POST "https://api.render.com/v1/services/<SERVICE_ID>/deploys" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
               -H "Accept: application/json" -d '{"clearCache":false}'
          # Purge Cloudflare cache
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
               -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
               -H "Content-Type: application/json" --data '{"purge_everything":true}'
          echo "✅ Instances réparées et synchronisées" >> logs/redundancy.log

      - name: 🧠 Ré-équilibrage du trafic
        run: |
          echo "⚙️ Calcul du trafic actif..."
          echo "Route active: Render → Cloudflare Backup" >> logs/redundancy.log

      - name: 📡 Notification Telegram (optionnelle)
        if: always()
        run: |
          if [ -n "${{ secrets.TELEGRAM_WEBHOOK }}" ]; then
            MSG="⚛️ Quantum Matrix Check OK – Redundancy active"
            curl -s -X POST ${{ secrets.TELEGRAM_WEBHOOK }} -d "text=$MSG"
          fi

      - name: 🗂️ Upload des logs
        uses: actions/upload-artifact@v4
        with:
          name: redundancy-matrix-logs
          path: logs/
