name: 🧠 Sentinel AutoFixer v5.0 — HealthAgent + CDNHeal + Telegram + Console IA

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  sentinel-autofix:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout du dépôt
        uses: actions/checkout@v4

      - name: 🧩 Vérifie et recrée les dossiers essentiels
        run: |
          mkdir -p public/dashboard public/documentation public/admin/agents
          touch public/dashboard/.keep public/documentation/.keep
          echo "✅ Vérification terminée."

      - name: 💾 Commit automatique si changement
        run: |
          git config --global user.name "Sentinel AutoFixer"
          git config --global user.email "autofix@sentinel.local"
          git add public/dashboard/.keep public/documentation/.keep || true
          git diff --cached --quiet || git commit -m "🧠 AutoFixer : Dossiers recréés automatiquement"
          git push || echo "ℹ️ Aucun changement détecté"

      - name: ☁️ Déploiement Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "sentinelquantumvanguardaipro"
          directory: "dist"

      - name: 🩺 HealthAgent — Vérification des URLs clés
        id: health
        run: |
          URLS=(
            "https://sentinelquantumvanguardaipro.pages.dev"
            "https://sentinelquantumvanguardaipro.pages.dev/dashboard/"
            "https://sentinelquantumvanguardaipro.pages.dev/documentation/"
            "https://sentinelquantumvanguardaipro.pages.dev/status/"
          )
          echo "🔍 Vérification des pages principales..."
          STATUS_REPORT=""
          ERRORS=0
          for URL in "\${URLS[@]}"; do
            HTTP_CODE=$(curl -o /dev/null -s -w "%{http_code}" "\$URL")
            if [ "\$HTTP_CODE" = "200" ]; then
              STATUS_REPORT+="✅ OK (\$HTTP_CODE) — \$URL\n"
            else
              STATUS_REPORT+="⚠️ ERREUR (\$HTTP_CODE) — \$URL\n"
              ERRORS=$((ERRORS+1))
            fi
          done
          echo -e "\$STATUS_REPORT" > health_report.txt
          echo "ERREURS=\$ERRORS" >> \$GITHUB_ENV
          cat health_report.txt

      - name: 🧹 CDNHeal — Purge Cloudflare si erreur
        if: env.ERREURS != 0
        run: |
          echo "🚨 Erreur détectée — purge du cache Cloudflare..."
          curl -X POST "https://api.cloudflare.com/client/v4/zones/\${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer \${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
          echo "🧼 Cache Cloudflare purgé avec succès."

      - name: 🧠 Génération console IA /admin/agents
        run: |
          mkdir -p public/admin/agents
          DATE=$(date '+%Y-%m-%d %H:%M:%S UTC')
          cat > public/admin/agents/index.html <<HTML
          <!DOCTYPE html>
          <html lang="fr">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <title>Sentinel IA Console — Agents Monitor</title>
            <style>
              body {background:#000;color:#0ff;font-family:monospace;margin:0;padding:20px;}
              h1{color:#00ffff;text-shadow:0 0 10px #0ff;}
              .log{background:#0a0a0a;border:1px solid #033;padding:15px;margin-top:10px;border-radius:8px;}
              .ok{color:#00ff9d;} .warn{color:#ffb347;} .err{color:#ff6b6b;}
              footer{margin-top:30px;font-size:12px;color:#0cc;}
            </style>
          </head>
          <body>
            <h1>🛰️ Sentinel AI Agents — Console Live</h1>
            <div class="log">
              <pre>$(cat health_report.txt)</pre>
            </div>
            <footer>Dernière mise à jour : \$DATE</footer>
          </body>
          </html>
          HTML

      - name: 📲 Notification Telegram
        if: always()
        run: |
          STATUS="✅ Déploiement réussi"
          if [ "\${{ job.status }}" != "success" ]; then STATUS="⚠️ Erreur détectée"; fi

          MSG="🤖 *Sentinel AutoFixer v5.0*\n\n\${STATUS}\n\n🩺 *Rapport HealthAgent :*\n$(cat health_report.txt)\n\n🌍 [Accéder au site](https://sentinelquantumvanguardaipro.pages.dev)\n\n🧠 [Console IA Agents] (https://sentinelquantumvanguardaipro.pages.dev/admin/agents/)"

          if [ -n "\${{ secrets.TELEGRAM_BOT_TOKEN }}" ] && [ -n "\${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            curl -s -X POST "https://api.telegram.org/bot\${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d chat_id="\${{ secrets.TELEGRAM_CHAT_ID }}" \
              -d parse_mode="Markdown" \
              -d text="\$MSG"
          else
            echo "⚙️ Telegram désactivé (secrets manquants)"
          fi
