name: 🧠 Sentinel Quantum Vanguard AI Pro – Auto-Heal + Auto-Rollback CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  BOT_TOKEN: "7630324617:AAGYNTiOIhHFDyT83Qt_DezDUxEzEJf-K9E"
  CHAT_ID: "5707814118"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout du dépôt
        uses: actions/checkout@v4

      - name: 🧩 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 📦 Installation des dépendances
        id: deps
        run: |
          echo "📦 Installation..." | tee deploy.log
          npm install --legacy-peer-deps --force --no-audit --no-fund 2>&1 | tee -a deploy.log
        continue-on-error: true

      - name: 🏗️ Build du projet
        id: build
        run: |
          echo "🏗️ Build du projet..." | tee -a deploy.log
          npm run build 2>&1 | tee -a deploy.log
        continue-on-error: true

      - name: 🌐 Déploiement Cloudflare Pages
        id: deploy
        run: |
          npm install -g wrangler 2>&1 | tee -a deploy.log
          wrangler pages deploy dist --project-name=sentinelquantumvanguardaipro 2>&1 | tee -a deploy.log
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        continue-on-error: true

      - name: 🧾 Vérification du statut
        id: check
        run: |
          if [ "${{ steps.deps.outcome }}" == "failure" ]; then
            echo "status=deps_failed" >> $GITHUB_ENV
          elif [ "${{ steps.build.outcome }}" == "failure" ]; then
            echo "status=build_failed" >> $GITHUB_ENV
          elif [ "${{ steps.deploy.outcome }}" == "failure" ]; then
            echo "status=deploy_failed" >> $GITHUB_ENV
          else
            echo "status=success" >> $GITHUB_ENV
          fi

      - name: 📡 Notification Telegram
        if: always()
        run: |
          MSG="🛰️ *Sentinel Quantum Vanguard AI Pro – Rapport CI/CD*%0A"
          MSG+="⏰ $(date '+%Y-%m-%d %H:%M:%S')%0A"

          case "${{ env.status }}" in
            deps_failed)   MSG+="❌ *Échec npm install*" ;;
            build_failed)  MSG+="❌ *Échec du build*" ;;
            deploy_failed) MSG+="⚠️ *Erreur Cloudflare Pages*" ;;
            success)       MSG+="✅ *Déploiement réussi* 🚀" ;;
            *)             MSG+="⚙️ *Statut inconnu*" ;;
          esac

          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
               -d chat_id="${CHAT_ID}" -d parse_mode="Markdown" \
               --data-urlencode "text=$MSG"

          curl -s -F chat_id="${CHAT_ID}" -F document=@deploy.log \
               "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument"

      - name: 🔁 Auto-Heal (relance une fois)
        if: env.status != 'success'
        run: |
          echo "♻️ Tentative de redéploiement automatique..." | tee -a deploy.log
          gh workflow run "sentinel-autoheal-rollback.yml" --ref main --raw-field attempt="retry1"
          MSG="♻️ *Auto-Heal activé* : relance automatique du déploiement."
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
               -d chat_id="${CHAT_ID}" -d parse_mode="Markdown" \
               --data-urlencode "text=$MSG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🕹️ Auto-Rollback (si 2ᵉ tentative échoue)
        if: github.event.inputs.attempt == 'retry1' && env.status != 'success'
        run: |
          echo "⚠️ 2ᵉ tentative échouée – restauration du dernier commit stable..." | tee -a deploy.log
          git fetch origin main
          git reset --hard HEAD~1
          git push --force origin main
          MSG="🔁 *Auto-Rollback exécuté* : restauration du commit précédent stable."
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
               -d chat_id="${CHAT_ID}" -d parse_mode="Markdown" \
               --data-urlencode "text=$MSG"
