name: 🧠 Sentinel Auto-Recovery

on:
  workflow_run:
    workflows:
      - "🌌 Sentinel Nightly Health Monitor"
      - "🧩 Sentinel Auto-Healer"
      - "🛰 Sentinel Telemetry Watcher"
      - "🚀 Publish Sentinel Dashboard to Cloudflare Pages"
    types:
      - completed
  workflow_dispatch:

jobs:
  recovery:
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Vérification des workflows récents
        uses: actions/github-script@v7
        id: check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: runs } = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 10
            });
            const failed = runs.workflow_runs.find(r => r.conclusion === "failure");
            if (failed) {
              core.setOutput("failed_workflow_id", failed.id);
              core.notice(`❌ Workflow échoué détecté : ${failed.name}`);
            } else {
              core.notice("✅ Aucun workflow échoué récemment.");
            }

      - name: 🚀 Relancer automatiquement le dernier workflow échoué
        if: steps.check.outputs.failed_workflow_id
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.reRunWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ steps.check.outputs.failed_workflow_id }}
            });
            core.notice("🩹 Workflow échoué relancé automatiquement avec succès.");

      - name: 📡 Notification Telegram
        run: |
          MSG="🧠 Sentinel Auto-Recovery exécuté.\n"
          if [ -n "${{ steps.check.outputs.failed_workflow_id }}" ]; then
            MSG="${MSG}🔁 Un workflow a été relancé automatiquement."
          else
            MSG="${MSG}✅ Aucun échec détecté."
          fi
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MSG\n🕒 $(date)"

      - name: ✅ Fin du cycle Auto-Recovery
        run: echo "✔️ Sentinel Auto-Recovery terminé avec succès."