name: 🛡️ Sentinel Security Pulse

on:
  schedule:
    - cron: '0 */6 * * *' # toutes les 6 heures
  workflow_dispatch:

jobs:
  security_audit:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 📦 Installer les dépendances
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: 🔍 Audit sécurité PNPM
        run: |
          mkdir -p security
          pnpm audit --json > security/pnpm-audit.json || true
          echo "✅ Audit PNPM terminé"

      - name: 🔍 Audit sécurité NPM
        run: |
          npm audit --json > security/npm-audit.json || true
          echo "✅ Audit NPM terminé"

      - name: 🧩 Scanner les signatures de modules IA
        run: |
          echo "🔬 Analyse des modules sensibles IA..."
          grep -i "openai\\|gemini\\|deepl\\|firebase\\|supabase" package.json > security/ai-modules.txt || echo "Aucun module IA détecté" > security/ai-modules.txt
          echo "✅ Scan des modules IA terminé"

      - name: 🧠 Génération du rapport HTML
        run: |
          mkdir -p public/security
          echo "<html><head><title>Sentinel Security Pulse</title><meta http-equiv='refresh' content='600'></head><body style='font-family:monospace;background:#0d1117;color:#e6edf3;padding:20px;'>" > public/security/index.html
          echo "<h2>🛡️ Sentinel Security Pulse</h2><hr>" >> public/security/index.html
          echo "<h3>📦 PNPM Audit</h3><pre>" >> public/security/index.html
          jq '.advisories // .vulnerabilities // {}' security/pnpm-audit.json >> public/security/index.html || echo "Aucune vulnérabilité critique détectée." >> public/security/index.html
          echo "</pre><h3>📦 NPM Audit</h3><pre>" >> public/security/index.html
          jq '.advisories // .vulnerabilities // {}' security/npm-audit.json >> public/security/index.html || echo "Aucune vulnérabilité critique détectée." >> public/security/index.html
          echo "</pre><h3>🤖 Modules IA détectés</h3><pre>" >> public/security/index.html
          cat security/ai-modules.txt >> public/security/index.html
          echo "</pre><hr><p>🕒 Dernière mise à jour : $(date)</p></body></html>" >> public/security/index.html
          echo "✅ Rapport HTML généré"

      - name: 🚀 Publier le rapport sur Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sentinelquantumvanguardaipro
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: 📡 Envoyer résumé sur Telegram
        run: |
          ALERTS=$(jq length security/pnpm-audit.json)
          MSG="🛡️ Sentinel Security Pulse\nVulnérabilités critiques : ${ALERTS}\nModules IA scannés : $(wc -l < security/ai-modules.txt)\n🕒 $(date)"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="$MSG"

      - name: ✅ Fin du cycle Security Pulse
        run: echo "✔️ Sentinel Security Pulse terminé avec succès."