name: 🤖 Sentinel AutoFixer + HealthAgent + Telegram

on:
  schedule:
    - cron: "*/30 * * * *"   # toutes les 30 minutes
  workflow_dispatch:

jobs:
  sentinel-autofix:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout du dépôt
        uses: actions/checkout@v4

      - name: 🧩 Vérifie et recrée les dossiers essentiels
        run: |
          mkdir -p public/dashboard public/documentation
          touch public/dashboard/.keep
          touch public/documentation/.keep
          echo "✅ Vérification des répertoires terminée."

      - name: 💾 Commit automatique si changement détecté
        run: |
          git config --global user.name "Sentinel AutoFixer"
          git config --global user.email "autofix@sentinel.local"
          git add public/dashboard/.keep public/documentation/.keep || true
          git diff --cached --quiet || git commit -m "🧠 AutoFixer : dossiers recréés automatiquement"
          git push || echo "ℹ️ Aucun changement à pousser"

      - name: ☁️ Déploiement Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "sentinelquantumvanguardaipro"
          directory: "dist"

      - name: 🩺 Vérification HealthAgent (accessibilité URLs)
        id: health
        run: |
          URLS=(
            "https://sentinelquantumvanguardaipro.pages.dev"
            "https://sentinelquantumvanguardaipro.pages.dev/dashboard/perf.html"
            "https://sentinelquantumvanguardaipro.pages.dev/documentation/index.html"
            "https://sentinelquantumvanguardaipro.pages.dev/status.html"
          )
          echo "🔍 Vérification de l'accessibilité des pages..."
          STATUS_REPORT=""
          for URL in "\${URLS[@]}"; do
            HTTP_CODE=$(curl -o /dev/null -s -w "%{http_code}" "\$URL")
            if [ "\$HTTP_CODE" = "200" ]; then
              STATUS_REPORT+="✅ OK : \$URL\n"
            else
              STATUS_REPORT+="⚠️ ERREUR (\$HTTP_CODE) : \$URL\n"
            fi
          done
          echo -e "\$STATUS_REPORT" > health_report.txt
          echo "🩺 Rapport d'état généré."

      - name: 📲 Notification Telegram
        if: always()
        run: |
          STATUS="✅ Déploiement réussi"
          if [ "\${{ job.status }}" != "success" ]; then STATUS="⚠️ Erreur détectée"; fi

          MSG="🛰 *Sentinel AutoFixer*\n\n\${STATUS}\n\n*Détails HealthAgent :*\n$(cat health_report.txt)\n\n🌍 [Accéder au site](https://sentinelquantumvanguardaipro.pages.dev)"

          if [ -n "\${{ secrets.TELEGRAM_BOT_TOKEN }}" ] && [ -n "\${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            curl -s -X POST "https://api.telegram.org/bot\${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d chat_id="\${{ secrets.TELEGRAM_CHAT_ID }}" \
              -d parse_mode="Markdown" \
              -d text="\$MSG"
          else
            echo "⚙️ Telegram désactivé (secrets manquants)"
          fi
