name: 🔁 Sentinel – Auto Redeploy (every 30 min)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v4

      - name: 🧩 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 📦 Install deps (ci)
        run: npm ci

      - name: ⚙️ Build (prod + logs)
        run: |
          echo "🚀 Build Sentinel v3.3 (prod + debug logs)"
          npm run build || echo "⚠️ Build terminé avec avertissements (Service Worker ignoré si non supporté)"

      - name: 🌐 Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "sentinelquantumvanguardaipro"
          directory: "dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Healthcheck summary
        if: always()
        run: |
          echo "Site: https://sentinelquantumvanguardaipro.pages.dev"
          echo "Docs: https://sentinelquantumvanguardaipro.pages.dev/documentation/"
          echo "3D  : https://sentinelquantumvanguardaipro.pages.dev/architecture3d.html"

      - name: 📡 Telegram notify (optional)
        if: always()
        run: |
          if [ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ] && [ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            MSG="🔁 Sentinel auto-redeploy OK (30 min cadence)\n🌐 Site: https://sentinelquantumvanguardaipro.pages.dev"
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" -d text="$MSG" >/dev/null
          else
            echo "ℹ️ Telegram désactivé (secrets manquants)."
          fi
