name: ♻️ Wave 16 – Sentinel AI Self-Healing Kernel (Auto-Recovery & Workflow Repair)

on:
  schedule:
    - cron: "*/20 * * * *"     # toutes les 20 minutes
  workflow_dispatch:

jobs:
  selfheal:
    runs-on: ubuntu-latest
    name: 🧠 Sentinel Self-Healing Core
    steps:
      - name: 🚀 Initialisation
        run: |
          echo "♻️ Démarrage du noyau Self-Healing..."
          mkdir -p logs
          echo "$(date '+%F %T') | Lancement Wave 16" >> logs/selfheal.log

      - name: 🩺 Scan des Workflows GitHub
        run: |
          echo "Analyse des dernières exécutions..."
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=10" > logs/actions.json
          ERRORS=$(grep -c '"conclusion":"failure"' logs/actions.json || echo 0)
          echo "errors=$ERRORS" >> $GITHUB_OUTPUT
          echo "$(date '+%T') | Workflows en erreur : $ERRORS" >> logs/selfheal.log

      - name: 🧬 Réparation Render / Cloudflare
        if: ${{ steps.scan.outputs.errors > 0 }}
        run: |
          echo "Une ou plusieurs erreurs détectées – déclenchement rebuild."
          curl -s -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
          curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
               -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
               -H "Content-Type: application/json" --data '{"purge_everything":true}'
          echo "Rebuild Render + purge Cloudflare effectués." >> logs/selfheal.log

      - name: 🔄 Mise à jour automatique des modules
        run: |
          echo "Vérification des modules npm/pnpm..."
          npm install --omit=dev || pnpm install
          echo "$(date '+%T') | Modules mis à jour si nécessaire" >> logs/selfheal.log

      - name: 🧠 Auto-Commit des correctifs (minor)
        run: |
          git config --global user.name "Sentinel-AI-Kernel"
          git config --global user.email "ai-kernel@sentinel"
          git add .
          git commit -m "♻️ Self-Healing Kernel – auto-repair $(date +%T)" || echo "Aucune modification à commettre"
          git push || echo "Push non nécessaire"

      - name: 📲 Notification Telegram (optionnelle)
        if: always()
        run: |
          if [ -n "${{ secrets.TELEGRAM_WEBHOOK }}" ]; then
            MSG="♻️ Self-Healing executé – erreurs:${{ steps.scan.outputs.errors }}"
            curl -s -X POST ${{ secrets.TELEGRAM_WEBHOOK }} -d "text=$MSG"
          fi

      - name: 📜
- name: 📜 Upload des logs
        uses: actions/upload-artifact@v4
        with:
          name: sentinel-selfheal-logs
          path: logs/
